version: 2

jobs:
  bionic_gcc7_coverage:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_coverage.sh
  cosmic_gcc8_asan:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_gcc8_asan.sh
  cosmic_clang7:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_clang7.sh
  bionic_clang6_release:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_clang6_release.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - bionic_gcc7_coverage
    - cosmic_gcc8_asan
    - cosmic_clang7
    - bionic_clang6_release
    